# Generated by Django 4.1.5 on 2023-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_active_quiz_created_alter_user_score_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='points',
        ),
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
